module.exports = {
  COMMUNITY_CHAT: "COMMUNITY_CHAT",
  USER_CONNECTED: "USER_CONNECTED",
  MESSAGE_RECIVED: "MESSAGE_RECIVED",
  MESSAGE_SENT: "COMMUNITY_CHAT",
  USER_DISCONNECTED: "USER_DISCONNECTED",
  TYPING: "TYPING",
  VERIFY_USER: "VERIFY_USER",
  LOGOUT: "LOGOUT",
};